### ISSUE TITLE
Multiplayer support ?

### ISSUE THREAD

**Issue by zilveer** [Cysha/casino#1]
Hi,
Will there be multiplayer support for this package ?if yes, how will you handle the realtime playing mode, will sockets be used here ?

Regards

**Comment by NoelDavies** [comment]
There is multiplayer support for this, as the library models a basic casino setup. You'd have to manage the implementation for your use-case, but everything is there to be used for it. We currently have it setup as a Telegram, (Slack? @xLink ) and IRC bot.
